.PHONY: all build_zic run screenshot clean

all:
	$(MAKE) -C emu all

build_zic:
	$(MAKE) -C emu build_zic

run:
	$(MAKE) -C emu run

screenshot:
	$(MAKE) -C emu screenshot

clean:
	$(MAKE) -C emu clean
