--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
local ____core = require("config.libs.core")
local applyZic = ____core.applyZic
local React = require("config.libs.react")
local ____ui = require("config.libs.ui")
local addZoneEncoder = ____ui.addZoneEncoder
local setScreenSize = ____ui.setScreenSize
local setWindowPosition = ____ui.setWindowPosition
local ____constants = require("config.pixel.240x320_kick.ui.constants")
local ScreenHeight = ____constants.ScreenHeight
local ScreenWidth = ____constants.ScreenWidth
local W1_2 = ____constants.W1_2
local ____AmpView = require("config.pixel.240x320_kick.ui.Drum23.AmpView")
local AmpView = ____AmpView.AmpView
local ____ClickView = require("config.pixel.240x320_kick.ui.Drum23.ClickView")
local ClickView = ____ClickView.ClickView
local ____DistortionView = require("config.pixel.240x320_kick.ui.Drum23.DistortionView")
local DistortionView = ____DistortionView.DistortionView
local ____Drum23View = require("config.pixel.240x320_kick.ui.Drum23.Drum23View")
local Drum23View = ____Drum23View.Drum23View
local ____FrequencyView = require("config.pixel.240x320_kick.ui.Drum23.FrequencyView")
local FrequencyView = ____FrequencyView.FrequencyView
local ____SeqView = require("config.pixel.240x320_kick.ui.Drum23.SeqView")
local Drum23SeqView = ____SeqView.Drum23SeqView
local ____WaveformView = require("config.pixel.240x320_kick.ui.Drum23.WaveformView")
local WaveformView = ____WaveformView.WaveformView
local ____DrumsSeqView = require("config.pixel.240x320_kick.ui.DrumsSeq.DrumsSeqView")
local DrumsSeqView = ____DrumsSeqView.DrumsSeqView
local ____Fm2View = require("config.pixel.240x320_kick.ui.Fm.Fm2View")
local Fm2View = ____Fm2View.Fm2View
local ____FmView = require("config.pixel.240x320_kick.ui.Fm.FmView")
local FmView = ____FmView.FmView
local ____HiHat2View = require("config.pixel.240x320_kick.ui.HiHat.HiHat2View")
local HiHat2View = ____HiHat2View.HiHat2View
local ____HiHatView = require("config.pixel.240x320_kick.ui.HiHat.HiHatView")
local HiHatView = ____HiHatView.HiHatView
local ____CreateWorkspaceView = require("config.pixel.240x320_kick.ui.menu.CreateWorkspaceView")
local CreateWorkspaceView = ____CreateWorkspaceView.CreateWorkspaceView
local ____menuView = require("config.pixel.240x320_kick.ui.menu.menuView")
local MenuView = ____menuView.MenuView
local ____ShutdownView = require("config.pixel.240x320_kick.ui.menu.ShutdownView")
local ShutdownView = ____ShutdownView.ShutdownView
local ____WorkspacesView = require("config.pixel.240x320_kick.ui.menu.WorkspacesView")
local WorkspacesView = ____WorkspacesView.WorkspacesView
local ____Perc2View = require("config.pixel.240x320_kick.ui.Perc.Perc2View")
local Perc2View = ____Perc2View.Perc2View
local ____PercView = require("config.pixel.240x320_kick.ui.Perc.PercView")
local PercView = ____PercView.PercView
local ____Snare2View = require("config.pixel.240x320_kick.ui.Snare.Snare2View")
local Snare2View = ____Snare2View.Snare2View
local ____SnareView = require("config.pixel.240x320_kick.ui.Snare.SnareView")
local SnareView = ____SnareView.SnareView
setWindowPosition(400, 500)
setScreenSize(ScreenWidth, ScreenHeight)
local halfHeight = ScreenHeight / 2
addZoneEncoder({0, 0, W1_2, halfHeight})
addZoneEncoder({0, halfHeight, W1_2, halfHeight})
addZoneEncoder({W1_2, 0, W1_2, halfHeight})
addZoneEncoder({W1_2, halfHeight, W1_2, halfHeight})
applyZic(React.createElement(Drum23View, {name = "Drum23"}))
applyZic(React.createElement(DistortionView, {name = "Distortion"}))
applyZic(React.createElement(WaveformView, {name = "Waveform"}))
applyZic(React.createElement(FrequencyView, {name = "Frequency"}))
applyZic(React.createElement(AmpView, {name = "Amplitude"}))
applyZic(React.createElement(ClickView, {name = "Click"}))
applyZic(React.createElement(Drum23SeqView, {name = "Sequencer"}))
applyZic(React.createElement(SnareView, {name = "Snare"}))
applyZic(React.createElement(Snare2View, {name = "Snare2"}))
applyZic(React.createElement(HiHatView, {name = "HiHat"}))
applyZic(React.createElement(HiHat2View, {name = "HiHat2"}))
applyZic(React.createElement(FmView, {name = "Fm"}))
applyZic(React.createElement(Fm2View, {name = "Fm2"}))
applyZic(React.createElement(PercView, {name = "Perc"}))
applyZic(React.createElement(Perc2View, {name = "Perc2"}))
applyZic(React.createElement(DrumsSeqView, {name = "DrumsSeq"}))
applyZic(React.createElement(MenuView, {name = "Menu"}))
applyZic(React.createElement(WorkspacesView, {name = "Workspaces"}))
applyZic(React.createElement(CreateWorkspaceView, {name = "CreateWorkspace"}))
applyZic(React.createElement(ShutdownView, {name = "Shutdown"}))
return ____exports
