--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
local ____core = require("config.libs.core")
local applyZic = ____core.applyZic
local React = require("config.libs.react")
local ____ui = require("config.libs.ui")
local addZoneEncoder = ____ui.addZoneEncoder
local setScreenSize = ____ui.setScreenSize
local setWindowPosition = ____ui.setWindowPosition
local ____constants = require("config.pixel.240x320_kick.ui.constants")
local ScreenHeight = ____constants.ScreenHeight
local ScreenWidth = ____constants.ScreenWidth
local W1_2 = ____constants.W1_2
local ____AmpView = require("config.pixel.240x320_kick.ui.Drum23.AmpView")
local AmpView = ____AmpView.AmpView
local ____ClickView = require("config.pixel.240x320_kick.ui.Drum23.ClickView")
local ClickView = ____ClickView.ClickView
local ____DistortionView = require("config.pixel.240x320_kick.ui.Drum23.DistortionView")
local DistortionView = ____DistortionView.DistortionView
local ____FrequencyView = require("config.pixel.240x320_kick.ui.Drum23.FrequencyView")
local FrequencyView = ____FrequencyView.FrequencyView
local ____MasterView = require("config.pixel.240x320_kick.ui.Drum23.MasterView")
local MasterView = ____MasterView.MasterView
local ____WaveformView = require("config.pixel.240x320_kick.ui.Drum23.WaveformView")
local WaveformView = ____WaveformView.WaveformView
local ____CreateWorkspaceView = require("config.pixel.240x320_kick.ui.menu.CreateWorkspaceView")
local CreateWorkspaceView = ____CreateWorkspaceView.CreateWorkspaceView
local ____menuView = require("config.pixel.240x320_kick.ui.menu.menuView")
local MenuView = ____menuView.MenuView
local ____ShutdownView = require("config.pixel.240x320_kick.ui.menu.ShutdownView")
local ShutdownView = ____ShutdownView.ShutdownView
local ____WorkspacesView = require("config.pixel.240x320_kick.ui.menu.WorkspacesView")
local WorkspacesView = ____WorkspacesView.WorkspacesView
local ____Seq = require("config.pixel.240x320_kick.ui.Seq.index")
local SeqView = ____Seq.SeqView
local ____Snare2View = require("config.pixel.240x320_kick.ui.Snare.Snare2View")
local Snare2View = ____Snare2View.Snare2View
local ____SnareView = require("config.pixel.240x320_kick.ui.Snare.SnareView")
local SnareView = ____SnareView.SnareView
setWindowPosition(400, 500)
setScreenSize(ScreenWidth, ScreenHeight)
local halfHeight = ScreenHeight / 2
addZoneEncoder({0, 0, W1_2, halfHeight})
addZoneEncoder({0, halfHeight, W1_2, halfHeight})
addZoneEncoder({W1_2, 0, W1_2, halfHeight})
addZoneEncoder({W1_2, halfHeight, W1_2, halfHeight})
applyZic(React.createElement(MasterView, {name = "Master"}))
applyZic(React.createElement(DistortionView, {name = "Distortion"}))
applyZic(React.createElement(WaveformView, {name = "Waveform"}))
applyZic(React.createElement(FrequencyView, {name = "Frequency"}))
applyZic(React.createElement(AmpView, {name = "Amplitude"}))
applyZic(React.createElement(ClickView, {name = "Click"}))
applyZic(React.createElement(SeqView, {name = "Sequencer"}))
applyZic(React.createElement(SnareView, {name = "Snare"}))
applyZic(React.createElement(Snare2View, {name = "Snare2"}))
applyZic(React.createElement(MenuView, {name = "Menu"}))
applyZic(React.createElement(WorkspacesView, {name = "Workspaces"}))
applyZic(React.createElement(CreateWorkspaceView, {name = "CreateWorkspace"}))
applyZic(React.createElement(ShutdownView, {name = "Shutdown"}))
return ____exports
