[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200

build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DINIT_SEQUENCE_3=1
    -DCGRAM_OFFSET=1
    -DTFT_RGB_ORDER=TFT_RGB
    -DTFT_INVERSION_ON=1
    -DTFT_PARALLEL_8_BIT=1
    -DTFT_WIDTH=170
    -DTFT_HEIGHT=320
    -DTFT_CS=6
    -DTFT_DC=7
    -DTFT_RST=5
    -DTFT_WR=8
    -DTFT_RD=9
    -DTFT_D0=39
    -DTFT_D1=40
    -DTFT_D2=41
    -DTFT_D3=42
    -DTFT_D4=45
    -DTFT_D5=46
    -DTFT_D6=47
    -DTFT_D7=48
    -DTFT_BL=38
    -DTFT_BACKLIGHT_ON=1
    -DTOUCH_SDA=18
    -DTOUCH_SCL=17
    -DSEESAW_NO_DAC
    -DSCREEN_BUFFER_ROWS=170
    -DSCREEN_BUFFER_COLS=320
    -I.
    -I../../
    -I../

lib_deps =
    bodmer/TFT_eSPI@^2.5.31
    adafruit/Adafruit seesaw Library
    Wire
    SPI
    Preferences

