$width=100

createView: Granular, HIDDEN
  include: layout.ui

  if: $width, <, 100
    addComponent: EncoderIsFalse, 0, 430, $width, 50
      setEncoderId: 1
      value: Sequencer, STEP_NOTE

  $i=0
  while: $i, <, 5
    addComponent: EncoderLoop, $i, 430, $width * 2, 50
    $i=$i + 1

  # $i=$i + 1
  # addComponent: Yo, $i * 100, 50.5, 100.50
  #   label: Some string with var $i in the middle

  # if: abc, ==, abc