--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports.ScreenWidth = 240
____exports.ScreenHeight = 320
____exports.W1_4 = ____exports.ScreenWidth / 4
____exports.W2_4 = ____exports.W1_4 * 2
____exports.W1_2 = ____exports.W2_4
____exports.W3_4 = ____exports.W1_4 * 3
____exports.W1_8 = ____exports.ScreenWidth / 8
____exports.W2_8 = ____exports.W1_8 * 2
____exports.W3_8 = ____exports.W1_8 * 3
____exports.W4_8 = ____exports.W1_8 * 4
____exports.W5_8 = ____exports.W1_8 * 5
____exports.W6_8 = ____exports.W1_8 * 6
____exports.W7_8 = ____exports.W1_8 * 7
____exports.W8_8 = ____exports.W1_8 * 8
____exports.KeyInfoPosition = {0, 296, ____exports.W3_4}
____exports.KeyInfoPositionCenter = {____exports.W1_8, ____exports.KeyInfoPosition[2], ____exports.KeyInfoPosition[3]}
____exports.PrimaryBar = "#377275"
____exports.SecondaryBar = "#b54f5e"
____exports.TertiaryBar = "#368a36"
____exports.QuaternaryBar = "#94854b"
____exports.ColorTrack1 = "#fd6f0e"
____exports.ColorTrack2 = "#ffcd04"
____exports.ColorTrack3 = "#a3c912"
____exports.ColorTrack4 = "#23a123"
____exports.ColorTrack5 = "#15a5ca"
____exports.ColorTrack6 = "#4643d8"
____exports.ColorTrack7 = "#902ed1"
____exports.ColorTrack8 = "#cb11ca"
return ____exports
