--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
local ____audio = require("config.libs.audio")
local autoSave = ____audio.autoSave
local plugin = ____audio.plugin
local pluginAlias = ____audio.pluginAlias
local ____constants = require("config.pixel.240x320.audio.constants")
local STRING_CUTOFF_FORMAT = ____constants.STRING_CUTOFF_FORMAT
local ____drum23 = require("config.pixel.240x320.audio.drum23")
local drum23 = ____drum23.drum23
local ____monoSample = require("config.pixel.240x320.audio.monoSample")
local monoSample = ____monoSample.monoSample
pluginAlias("EffectDistortion", "libzic_EffectDistortion.so")
pluginAlias("EffectDistortion2", "libzic_EffectDistortion2.so")
pluginAlias("EffectFilterMultiMode", "libzic_EffectFilterMultiMode.so")
pluginAlias("EffectSampleRateReducer", "libzic_EffectSampleRateReducer.so")
pluginAlias("EffectGainVolume", "libzic_EffectGainVolume.so")
pluginAlias("EffectVolumeDrive", "libzic_EffectVolumeDrive.so")
pluginAlias("EffectVolumeClipping", "libzic_EffectVolumeClipping.so")
pluginAlias("EffectDelay", "libzic_EffectDelay.so")
pluginAlias("Mixer2", "libzic_Mixer2.so")
pluginAlias("Mixer4", "libzic_Mixer4.so")
pluginAlias("Mixer8", "libzic_Mixer8.so")
pluginAlias("SerializeTrack", "libzic_SerializeTrack.so")
pluginAlias("Tempo", "libzic_Tempo.so")
pluginAlias("SynthFM", "libzic_SynthFM2.so")
pluginAlias("Drum23", "libzic_SynthDrum23.so")
pluginAlias("MonoSample", "libzic_SynthMonoSample.so")
pluginAlias("Sequencer", "libzic_Sequencer.so")
pluginAlias("AudioOutput", "libzic_AudioOutputPulse.so")
pluginAlias("Spectrogram", "libzic_AudioSpectrogram.so")
pluginAlias("Tape", "libzic_TapeRecording.so")
pluginAlias("RamTape", "libzic_RamTapeRecording.so")
drum23(1)
drum23(2)
monoSample(3)
monoSample(4)
plugin("MixerDrum Mixer4", {{track = 9}})
plugin("SerializeTrack", {{track = 9, filename = "mixer_drum"}})
monoSample(5)
monoSample(6)
monoSample(7)
monoSample(8)
plugin("MixerSynth Mixer4", {{track_start = 5, track = 10}})
plugin("SerializeTrack", {{track = 10, filename = "mixer_synth"}})
plugin("MixerMaster Mixer2", {{track_a = 9, track_b = 10, value = 50, track = 0}})
plugin("MasterFilter EffectFilterMultiMode", {{STRING_CUTOFF_FORMAT = STRING_CUTOFF_FORMAT}})
plugin("MasterVolume EffectGainVolume")
plugin("Spectrogram")
plugin("AudioOutput")
plugin("SerializeTrack", {{filename = "master"}})
plugin("Tape", {{filename = "rec"}})
plugin("Tempo")
autoSave(500)
return ____exports
