[env:esp32-s3-lcd-1_47]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DSCREEN_BUFFER_ROWS=172
    -DSCREEN_BUFFER_COLS=320
    -I.
    -I../../
    -I../

lib_deps =
    SPI
    Preferences
