[env:esp32-s3-lcd-1_47]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_INVERSION_ON=1
    -DTFT_WIDTH=172
    -DTFT_HEIGHT=320
    -DTFT_MOSI=45
    -DTFT_SCLK=40
    -DTFT_CS=42
    -DTFT_DC=41
    -DTFT_RST=39
    -DTFT_BL=48
    -DTFT_BACKLIGHT_ON=1
    -I.
    -I../../
    -I../

lib_deps =
    bodmer/TFT_eSPI@^2.5.31
    Preferences
