#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const PROJECT_DIR = path.resolve(__dirname, '..');
const WORKSPACE_DIR = path.resolve(PROJECT_DIR, '..');

const SRC_DIR = path.join(WORKSPACE_DIR, 'data', 'audio', 'samples');
const OUT_DIR = path.join(WORKSPACE_DIR, 'data', 'audio', 'samples_16_mono_22.05kHz');
const HEADER_OUT = path.join(PROJECT_DIR, 'samplesData.h');

if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
}

const DEFAULT_DRUM_FILES = [
    'snare_1.wav',
    '383010__thedcheck__clap-10.wav',
    '269720__ianstargem__electronic-closed-high-hat-1.wav',
    'hat_01.wav',
    '701297__8bitmyketison__metallic-perc-clap-02.wav',
    'tom_01.wav',
    '131251__skarznstryfe__psy-squeak-zap.wav',
    'kick_01.wav'
];

function convertSample(inPath, outPath) {
    try {
        execFileSync('sox', [inPath, '-r', '22050', '-c', '1', '-b', '16', outPath, 'trim', '0', '5'], { stdio: 'ignore' });
        return true;
    } catch (e1) {
        try {
            execFileSync('ffmpeg', ['-y', '-i', inPath, '-ar', '22050', '-ac', '1', '-sample_fmt', 's16', '-t', '5.0', outPath], { stdio: 'ignore' });
            return true;
        } catch (e2) {
            console.error(`Error converting ${inPath}: ${e2.message}`);
            return false;
        }
    }
}

function parseWavPCM16(filePath) {
    const buffer = fs.readFileSync(filePath);
    // Find 'data' chunk
    let dataOffset = -1;
    for (let i = 0; i < buffer.length - 4; i++) {
        if (buffer.toString('ascii', i, i + 4) === 'data') {
            dataOffset = i + 8;
            break;
        }
    }
    if (dataOffset === -1) {
        throw new Error('Could not find data chunk in ' + filePath);
    }
    const pcmData = buffer.subarray(dataOffset);
    const numSamples = Math.floor(pcmData.length / 2);
    const samples = new Int16Array(numSamples);
    for (let i = 0; i < numSamples; i++) {
        samples[i] = pcmData.readInt16LE(i * 2);
    }
    return samples;
}

function generateHeader(convertedFiles) {
    let lines = [];
    lines.push('// Auto-generated by scripts/convert_samples.js');
    lines.push('#pragma once');
    lines.push('#include <cstdint>');
    lines.push('');
    lines.push('struct SampleData {');
    lines.push('    const char* name;');
    lines.push('    uint32_t numSamples;');
    lines.push('    const int16_t* pcm;');
    lines.push('};');
    lines.push('');

    let tracksData = [];

    convertedFiles.forEach((fname, idx) => {
        const filePath = path.join(OUT_DIR, fname);
        if (!fs.existsSync(filePath)) return;

        const samples = parseWavPCM16(filePath);
        const varName = `g_sample_pcm_${idx}`;

        lines.push(`// Track ${idx}: ${fname} (${samples.length} samples @ 22.05 kHz)`);
        lines.push(`static const int16_t ${varName}[${samples.length}] = {`);

        let sampleStr = [];
        for (let i = 0; i < samples.length; i += 12) {
            let chunk = [];
            for (let j = i; j < Math.min(i + 12, samples.length); j++) {
                chunk.push(samples[j]);
            }
            sampleStr.push('    ' + chunk.join(', '));
        }
        lines.push(sampleStr.join(',\n'));
        lines.push('};');
        lines.push('');

        tracksData.push({ fname, numSamples: samples.length, varName });
    });

    lines.push(`static const SampleData g_presetSamples[${tracksData.length}] = {`);
    tracksData.forEach(t => {
        lines.push(`    { "${t.fname}", ${t.numSamples}, ${t.varName} },`);
    });
    lines.push('};');
    lines.push('');

    fs.writeFileSync(HEADER_OUT, lines.join('\n'));
    console.log(`Generated ${HEADER_OUT} with ${tracksData.length} embedded 22.05 kHz PCM samples (Node.js).`);
}

function main() {
    console.log(`[Node.js] Converting drum samples from ${SRC_DIR} to 22.05 kHz 16-bit mono...`);

    let convertedList = [];
    DEFAULT_DRUM_FILES.forEach(f => {
        const inP = path.join(SRC_DIR, f);
        if (fs.existsSync(inP)) {
            const outP = path.join(OUT_DIR, f);
            if (convertSample(inP, outP)) {
                convertedList.push(f);
            }
        }
    });

    if (fs.existsSync(SRC_DIR)) {
        const files = fs.readdirSync(SRC_DIR);
        files.forEach(f => {
            if ((f.endsWith('.wav') || f.endsWith('.WAV')) && !convertedList.includes(f) && convertedList.length < 12) {
                const inP = path.join(SRC_DIR, f);
                const outP = path.join(OUT_DIR, f);
                if (convertSample(inP, outP)) {
                    convertedList.push(f);
                }
            }
        });
    }

    generateHeader(convertedList.slice(0, 8));
}

main();
