customBuild:
	make RectComponent TextComponent WatchDataContextComponent PatternComponent ClipComponent GraphValueComponent ValueComponent SampleComponent HiddenValueComponent SequencerValueComponent KnobValueComponent SequencerCardComponent StringValComponent TextBoxComponent DrawComponent NoteGridComponent SavePresetComponent PresetComponent WorkspaceKnobComponent PixelsComponent
