customBuild:
	make KnobValueComponent RectComponent TextComponent StringValComponent ValueComponent GraphEncoderComponent ClipsComponent HiddenValueComponent SequencerValueComponent SequencerCardComponent KnobActionComponent SampleComponent WorkspaceKnobComponent PixelsComponent
