import * as React from '@/libs/react';

import { Keyboard2 } from '@/libs/nativeComponents/Keyboard2';
import { Bounds } from '@/libs/ui';
import {
    A1,
    A10,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    B1,
    B10,
    B2,
    B3,
    B4,
    B5,
    B6,
    B7,
    B8,
    B9,
    C1,
    C10,
    C2,
    C3,
    C4,
    C5,
    C6,
    C7,
    C8,
    C9,
    D1,
    D10,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,
    D9,
    shiftContext
} from '../constants';

export type Props = {
    redirectView?: string;
    audioPlugin?: string;
    dataId?: string;
    bounds: Bounds;
};

export function InputForm({ bounds, redirectView, audioPlugin, dataId }: Props) {
    return (
        <Keyboard2
            bounds={bounds}
            font="PoppinsLight_12"
            redirectView={redirectView}
            audioPlugin={audioPlugin}
            dataId={dataId}
            shiftContextId={shiftContext}
            keys={[
                { key: A1, action: '.type:1', context: { id: shiftContext, value: 0 } },
                { key: A1, action: '.type:-', context: { id: shiftContext, value: 1 } },
                { key: A2, action: '.type:2', context: { id: shiftContext, value: 0 } },
                { key: A2, action: '.type:=', context: { id: shiftContext, value: 1 } },
                { key: A3, action: '.type:3', context: { id: shiftContext, value: 0 } },
                { key: A3, action: '.type:_', context: { id: shiftContext, value: 1 } },
                { key: A4, action: '.type:4', context: { id: shiftContext, value: 0 } },
                { key: A4, action: '.type:.', context: { id: shiftContext, value: 1 } },
                { key: A5, action: '.type:5', context: { id: shiftContext, value: 0 } },
                { key: A5, action: '.type:!', context: { id: shiftContext, value: 1 } },
                { key: A6, action: '.type:6', context: { id: shiftContext, value: 0 } },
                { key: A6, action: '.type:%', context: { id: shiftContext, value: 1 } },
                { key: A7, action: '.type:7', context: { id: shiftContext, value: 0 } },
                { key: A7, action: '.type:&', context: { id: shiftContext, value: 1 } },
                { key: A8, action: '.type:8', context: { id: shiftContext, value: 0 } },
                { key: A8, action: '.type::', context: { id: shiftContext, value: 1 } },
                { key: A9, action: '.type:9', context: { id: shiftContext, value: 0 } },
                { key: A9, action: '.type:$', context: { id: shiftContext, value: 1 } },
                { key: A10, action: '.type:0', context: { id: shiftContext, value: 0 } },
                { key: A10, action: '.type:#', context: { id: shiftContext, value: 1 } },

                { key: B1, action: '.type:q', context: { id: shiftContext, value: 0 } },
                { key: B1, action: '.type:Q', context: { id: shiftContext, value: 1 } },
                { key: B2, action: '.type:w', context: { id: shiftContext, value: 0 } },
                { key: B2, action: '.type:W', context: { id: shiftContext, value: 1 } },
                { key: B3, action: '.type:e', context: { id: shiftContext, value: 0 } },
                { key: B3, action: '.type:E', context: { id: shiftContext, value: 1 } },
                { key: B4, action: '.type:r', context: { id: shiftContext, value: 0 } },
                { key: B4, action: '.type:R', context: { id: shiftContext, value: 1 } },
                { key: B5, action: '.type:t', context: { id: shiftContext, value: 0 } },
                { key: B5, action: '.type:T', context: { id: shiftContext, value: 1 } },
                { key: B6, action: '.type:y', context: { id: shiftContext, value: 0 } },
                { key: B6, action: '.type:Y', context: { id: shiftContext, value: 1 } },
                { key: B7, action: '.type:u', context: { id: shiftContext, value: 0 } },
                { key: B7, action: '.type:U', context: { id: shiftContext, value: 1 } },
                { key: B8, action: '.type:i', context: { id: shiftContext, value: 0 } },
                { key: B8, action: '.type:I', context: { id: shiftContext, value: 1 } },
                { key: B9, action: '.type:o', context: { id: shiftContext, value: 0 } },
                { key: B9, action: '.type:O', context: { id: shiftContext, value: 1 } },
                { key: B10, action: '.type:p', context: { id: shiftContext, value: 0 } },
                { key: B10, action: '.type:P', context: { id: shiftContext, value: 1 } },

                { key: C1, action: '.type:a', context: { id: shiftContext, value: 0 } },
                { key: C1, action: '.type:A', context: { id: shiftContext, value: 1 } },
                { key: C2, action: '.type:s', context: { id: shiftContext, value: 0 } },
                { key: C2, action: '.type:S', context: { id: shiftContext, value: 1 } },
                { key: C3, action: '.type:d', context: { id: shiftContext, value: 0 } },
                { key: C3, action: '.type:D', context: { id: shiftContext, value: 1 } },
                { key: C4, action: '.type:f', context: { id: shiftContext, value: 0 } },
                { key: C4, action: '.type:F', context: { id: shiftContext, value: 1 } },
                { key: C5, action: '.type:g', context: { id: shiftContext, value: 0 } },
                { key: C5, action: '.type:G', context: { id: shiftContext, value: 1 } },
                { key: C6, action: '.type:h', context: { id: shiftContext, value: 0 } },
                { key: C6, action: '.type:H', context: { id: shiftContext, value: 1 } },
                { key: C7, action: '.type:j', context: { id: shiftContext, value: 0 } },
                { key: C7, action: '.type:J', context: { id: shiftContext, value: 1 } },
                { key: C8, action: '.type:k', context: { id: shiftContext, value: 0 } },
                { key: C8, action: '.type:K', context: { id: shiftContext, value: 1 } },
                { key: C9, action: '.type:l', context: { id: shiftContext, value: 0 } },
                { key: C9, action: '.type:L', context: { id: shiftContext, value: 1 } },

                { key: C10, action: '.backspace' },

                { key: D1, action: '.type:z', context: { id: shiftContext, value: 0 } },
                { key: D1, action: '.type:Z', context: { id: shiftContext, value: 1 } },
                { key: D2, action: '.type:x', context: { id: shiftContext, value: 0 } },
                { key: D2, action: '.type:X', context: { id: shiftContext, value: 1 } },
                { key: D3, action: '.type:c', context: { id: shiftContext, value: 0 } },
                { key: D3, action: '.type:C', context: { id: shiftContext, value: 1 } },
                { key: D4, action: '.type:v', context: { id: shiftContext, value: 0 } },
                { key: D4, action: '.type:V', context: { id: shiftContext, value: 1 } },
                { key: D5, action: '.type:b', context: { id: shiftContext, value: 0 } },
                { key: D5, action: '.type:B', context: { id: shiftContext, value: 1 } },
                { key: D6, action: '.type:n', context: { id: shiftContext, value: 0 } },
                { key: D6, action: '.type:N', context: { id: shiftContext, value: 1 } },
                { key: D7, action: '.type:m', context: { id: shiftContext, value: 0 } },
                { key: D7, action: '.type:M', context: { id: shiftContext, value: 1 } },

                { key: D8, action: '.ok' },
                { key: D9, action: '.exit' },
                { key: D10, action: `contextToggle:${shiftContext}:1:0` },
            ]}
            keyLabels={[
                '1',
                '2',
                '3',
                '4',
                '5',
                '6',
                '7',
                '8',
                '9',
                '0',

                'q',
                'w',
                'e',
                'r',
                't',
                'y',
                'u',
                'i',
                'o',
                'p',

                'a',
                's',
                'd',
                'f',
                'g',
                'h',
                'j',
                'k',
                'l',
                '&icon::backspace::filled',

                'z',
                'x',
                'c',
                'v',
                'b',
                'n',
                'm',

                'Ok',
                'Exit',
                'Shift',
            ]}
            keyLabelsShifted={[
                '-',
                '=',
                '_',
                '.',
                '!',
                '%',
                '&',
                ':',
                '$',
                '#',

                'Q',
                'W',
                'E',
                'R',
                'T',
                'Y',
                'U',
                'I',
                'O',
                'P',

                'A',
                'S',
                'D',
                'F',
                'G',
                'H',
                'J',
                'K',
                'L',
                '&icon::backspace::filled',

                'Z',
                'X',
                'C',
                'V',
                'B',
                'N',
                'M',

                'Ok',
                'Exit',
                'Shift',
            ]}
            keyColors={[
                '#28535f',
                '#28535f',
                '#79a1a3',
                '#79a1a3',
                '#28535f',
                '#28535f',
                '#79a1a3',
                '#79a1a3',
                '#28535f',
                '#28535f',

                '#28535f',
                '#28535f',
                '#79a1a3',
                '#79a1a3',
                '#28535f',
                '#28535f',
                '#79a1a3',
                '#79a1a3',
                '#28535f',
                '#28535f',

                '#28535f',
                '#28535f',
                '#79a1a3',
                '#79a1a3',
                '#28535f',
                '#28535f',
                '#79a1a3',
                '#79a1a3',
                '#28535f',
                '#ffAAAA',

                '#28535f',
                '#28535f',
                '#79a1a3',
                '#79a1a3',
                '#28535f',
                '#28535f',
                '#79a1a3',
                '#ffAAAA',
                '#ffAAAA',
                '#ffAAAA',
            ]}
            controllerColors={[
                {
                    controller: 'Default',
                    colors: [
                        { key: A1, color: '#28535f' },
                        { key: A2, color: '#28535f' },
                        { key: A3, color: '#79a1a3' },
                        { key: A4, color: '#79a1a3' },
                        { key: A5, color: '#28535f' },
                        { key: A6, color: '#28535f' },
                        { key: A7, color: '#79a1a3' },
                        { key: A8, color: '#79a1a3' },
                        { key: A9, color: '#28535f' },
                        { key: A10, color: '#28535f' },

                        { key: B1, color: '#28535f' },
                        { key: B2, color: '#28535f' },
                        { key: B3, color: '#79a1a3' },
                        { key: B4, color: '#79a1a3' },
                        { key: B5, color: '#28535f' },
                        { key: B6, color: '#28535f' },
                        { key: B7, color: '#79a1a3' },
                        { key: B8, color: '#79a1a3' },
                        { key: B9, color: '#28535f' },
                        { key: B10, color: '#28535f' },

                        { key: C1, color: '#28535f' },
                        { key: C2, color: '#28535f' },
                        { key: C3, color: '#79a1a3' },
                        { key: C4, color: '#79a1a3' },
                        { key: C5, color: '#28535f' },
                        { key: C6, color: '#28535f' },
                        { key: C7, color: '#79a1a3' },
                        { key: C8, color: '#79a1a3' },
                        { key: C9, color: '#28535f' },
                        { key: C10, color: '#ffAAAA' },

                        { key: D1, color: '#28535f' },
                        { key: D2, color: '#28535f' },
                        { key: D3, color: '#79a1a3' },
                        { key: D4, color: '#79a1a3' },
                        { key: D5, color: '#28535f' },
                        { key: D6, color: '#28535f' },
                        { key: D7, color: '#79a1a3' },
                        { key: D8, color: '#ffAAAA' },
                        { key: D9, color: '#ffAAAA' },
                        { key: D10, color: '#ffAAAA' },
                    ],
                },
            ]}
        />
    );
}
